### PR TITLE
improve bash tests & fix extra-source-files

### LINKED ISSUE #13: Abstract test files missing from sdist
In the `extra-source-files` cabal field, we're missing the three "abstract" files,

* tests/format1/abstract-test-with-macros
* tests/format2/abstract-test-with-macros
* tests/format3/abstract-test-with-macros

This makes the three macro tests fail. Fix is easy, add 'em in there.

### PR DESCRIPTION
**Pull request by obfusk**
Fixes #13.

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks!

**Comment by simonmichael** [comment]
@obfusk I found the failing test output with sh confusing. What's the reason for testing the non-bash shell here, would it make sense if I drop it ?

**Comment by obfusk** [comment]
> @obfusk I found the failing test output with sh confusing. What's the reason for testing the non-bash shell here, would it make sense if I drop it ?

I thought it best to make the expected behaviour (i.e. failure) with a non-bash shell explicit.
It would also make sure the test results are not misleading should they be run on a system where `/bin/sh` behaves differently.

**Comment by simonmichael** [comment]
We have observed that this bash-specific test fails with non-bash, but I don't really see that as property we need to test and guarantee. Maybe sh changes some day and that test starts passing, should we care and report that as a failure ? I'm inclined to remove it for now.

**Comment by obfusk** [comment]
We've already seen what happens when someone uses `bash` as their normal shell and (not unreasonably) expects certain syntax like `$'...'` to work (#15).

If, for example, you have a system where `/bin/sh` behaves exactly like `/bin/bash` then the bash-only test not failing will tell you that your assumptions about "normal behaviour" for `/bin/sh` may be wrong. (I've been bitten by some bugs caused by subtle differences in behaviour between Linux and *BSD regarding e.g. `bash` and `wc` before, hence my -- perhaps unnecessary -- caution here.)

Having said that: since this is a faily minor concern, I'm happy to defer to your judgement :)

**Comment by simonmichael** [comment]
You could be right, but I'm not quite seeing exactly how it helps, or it seems rather rare, whereas tests are run and output is read often so my preference is to try and keep those simpler. But could you spell out a scenario where it prevents a problem ?

**Pull request merged**
