### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by obfusk**

### CODE REVIEW

**Comment by simonmichael** [comment]
Wonderful, thank you very much! Merging this one first.

**Comment by simonmichael** [comment]
I notice that CI is passing even though its final `make test` command currently returns a failing exit code. This seems odd, shouldn't it fail ?

**Comment by simonmichael** [comment]
In fact, I see CI is passing even with failing tests: https://github.com/simonmichael/shelltestrunner/runs/700752600

**Comment by obfusk** [comment]
Well, there's 1 test that's expected to fail: running the bash test with `/bin/sh`: https://github.com/simonmichael/shelltestrunner/blob/7e4e86d/Makefile#L75.

**Pull request merged**
